language: python
python:
  - '2.6'
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - make install
script:
  - make test
deploy:
  provider: pypi
  username: RyanMiller
  password:
    secure: SYHX/jmoz2S9s6jr4VMIAXaN4/DXGaS6VneBY7w6FXWDoUjcHMNi07vzMCVw7f3AkbtLrukJHfJGRyrtQxZwA4VOwMLesmdZa6gedSRvyDmo6XfCNs3MakqQn76hsADJ6tnCLvycvkweG/QpTR+ilyir3Kd8nWqDwZV3pPd7Vn+syj9XIL+nUG0A+U4eBJOWhLZJkQV/yiLnLNQ5SfMLDgwiDiBwGTQNO/n3OlHsvH7zax+5tiBkfu2hGznC6HdkHvb0YiqXIwAiNf3lcrKJg8H0DQPqCAHAKqTJrSpH6jduLU7xPFDd/8kA50riQMOu/lgZwiobcTO1VvnuRzTMRZLlZyic7gbA7PDq/A9EV6mCDBmpr60FkIyf6N6jdGa2asxVITzPeLFgdzV0PJUMp4Enx6ZVro9zKkRAr60Wz8IEDbLgV7/e9bAT4in2CASAVm/+XFdM5aR9vaZb9Sj8KQNiDsrW8A8bzxShUg82RJR/fr8X5v6mCxcV7wNb0/+JmoeJno+j5Q9fNwWf3NaCXRhAxw38nNV+Vbl3IwUigJpMK7WJinhGbZM9xnYcJCOTaE6K8aNzUiqoEhs2x88vJYQOg7rR/Sec9p/2EBs2AEFwFR3KwxtISiV2h1DgLI/VCv34LnPvbokJjG+7w15y7MPLg5bYqv5Jyl3azWe6lCE=
  on:
    tags: true
    python: '3.6'

